# Numpy Arrays

In [1]:
import numpy as np

In [3]:
my_List=[1,2,3,4]

In [5]:
arr=np.array(my_List)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_Lists=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr1=np.array(my_Lists)

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr1[0]

array([1, 2, 3])

In [11]:
arr1[0][0]

1

In [12]:
arr1[0][1]

2

In [14]:
np.arange(1,10)  #np.arrange(start,end,step)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
np.eye(4) #identitiy Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(3,3)  #Returns Numbers from Uniform Number Distribution between 0 to 1

array([[0.47316357, 0.99162596, 0.99135581],
       [0.03368482, 0.2512991 , 0.29411661],
       [0.08403361, 0.4309202 , 0.35797257]])

In [28]:
np.random.randn(2) #Returns Numbers from Standard Number Distribution between 0 to 1

array([ 1.7886961 , -0.16220724])

In [30]:
np.random.randn(3,3)

array([[-0.7828094 ,  0.10121004, -0.74786782],
       [-0.94917627, -1.02240102,  0.28426199],
       [-0.91111039, -1.38962153, -1.34520354]])

In [31]:
np.random.randint(1,100)

36

In [32]:
np.random.randint(1,100,10)

array([64, 16,  6, 64, 51, 35, 68, 71, 87, 76])

In [34]:
arr=np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
randr=np.random.randint(1,10,20)

In [37]:
randr

array([2, 8, 2, 2, 5, 1, 8, 1, 1, 1, 5, 5, 4, 6, 1, 2, 6, 6, 3, 5])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
randr.max()

8

In [40]:
randr.min()

1

In [42]:
randr.argmax()

1

In [44]:
arr1=np.arange(0,11)

In [45]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr1=arr1[0:4]

In [52]:
slice_of_arr1[:]=99

In [53]:
slice_of_arr1

array([99, 99, 99, 99])

In [54]:
arr1

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

# 2d Array

In [55]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
array_2d[0]

array([1, 2, 3])

In [58]:
array_2d[0][2]

3

In [61]:
array_2d[1,0] #arr[row,col]

4

In [64]:
array_2d[:1,:1,]

array([[1]])

In [66]:
array_2d[:2,:2,]

array([[1, 2],
       [4, 5]])

In [67]:
arr=np.arange(0,10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
bool_arr=arr>5

In [70]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([6, 7, 8, 9])

In [85]:
arr_2d=np.arange(10).reshape(5,2)

In [86]:
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
arr_2d[1:3,]

array([[2, 3],
       [4, 5]])

In [88]:
arr_2d[1:3,1:]

array([[3],
       [5]])